server:
    shutdown: graceful
    port: 8080

    http-client:
        connect-timeout: 5s
        read-timeout: 30s
        connection-ttl: 30s
        idle-connection-timeout: 5s
        cleaning-period: PT5s
    forward-headers-strategy: framework

spring:
    application:
        name: FX Comparator
    messages:
        encoding: UTF-8
    jackson:
        default-property-inclusion: non_empty
        time-zone: Europe/Prague
        serialization:
            write-dates-as-timestamps: false
        deserialization:
            fail-on-unknown-properties: false
            adjust-dates-to-context-time-zone: true

integration:
    cnb:
        uri: https://www.cnb.cz/
        path: cs/financni_trhy/devizovy_trh/kurzy_devizoveho_trhu

    frankfurter:
        uri: https://api.frankfurter.dev
        path: v1


management:
    server:
        port: 8088
    health:
        defaults:
            enabled: true
        mail:
            enabled: false
